#!/bin/bash

#Corpul principal al scriptului care transforma limita intr-un numar(daca nu este deja), opreste toate operatiile cand este impus -stop si ruleaza sub scripturile necesare 

cd "$(dirname $BASH_SOURCE)"

if [ "$(cat ./Storage/firsttimeuse)" = "1" ]
then
	sudo chmod 777 ./Storage/check
	./Storage/check
	if [ $? -eq 1  ]; then 
		echo 'Componentele necesare nu au putut fi instalate'
		exit 1
	fi
	echo "0" > ./Storage/firsttimeuse
fi

if [ "$1" = "-stop" ]
then
	for i in $(cat ./Storage/watchlist)
	do
		sudo cgdelete -g "memory:$i"
	done	
	echo " " > ./Storage/watchlist
	exit 0
fi

if [ "$1" = "-rm" ]
then
	shift
        while [ "$1." != "." ]
        do
                if [ "$1" = "-add" ]
		then
			shift
			break
		fi
		./Storage/watcher -rm $1
		shift
        done
fi

if [ "$1" = "." ]
then
	exit 0
fi

wlimit=$(echo "$1" | tr -d [kmg])

i=${1:((${#1}-1))}

if [ $wlimit -eq $wlimit ]
then
        shift
else
        echo "Eroare! Limita trebuie sa fie un numar natural"
fi

if [ "$i" = "k" ]
then
	wlimit=$(($wlimit*1024))
elif [ "$i" = "m" ]
then
	 wlimit=$(($(($wlimit*1024))*1024 ))
elif [ "$i" = "g" ]
then
	 wlimit=$(($(($(($wlimit*1024))*1024))*1024))
fi

unset i

while [ "$1." != "." ]
do
	./Storage/watcher -add $wlimit $1 
	shift
done

watch -n 5 ./Storage/auto </dev/null &>/dev/null &

exit 0
